In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_representation=[one_hot(words,voc_size)for words in sent]
one_hot_representation

[[892, 2802, 6729, 4444],
 [892, 2802, 6729, 6038],
 [892, 441, 6729, 2291],
 [4709, 996, 7618, 5911, 3552],
 [4709, 996, 7618, 5911, 715],
 [1335, 892, 7978, 6729, 6653],
 [1334, 8265, 6970, 5911]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_representation,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  892 2802 6729 4444]
 [   0    0    0    0  892 2802 6729 6038]
 [   0    0    0    0  892  441 6729 2291]
 [   0    0    0 4709  996 7618 5911 3552]
 [   0    0    0 4709  996 7618 5911  715]
 [   0    0    0 1335  892 7978 6729 6653]
 [   0    0    0    0 1334 8265 6970 5911]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 101ms/step


array([[[ 0.00316459,  0.03200897, -0.02498647,  0.04236316,
         -0.018163  ,  0.0423051 , -0.02483431, -0.00097876,
         -0.04993521,  0.02311223],
        [ 0.00316459,  0.03200897, -0.02498647,  0.04236316,
         -0.018163  ,  0.0423051 , -0.02483431, -0.00097876,
         -0.04993521,  0.02311223],
        [ 0.00316459,  0.03200897, -0.02498647,  0.04236316,
         -0.018163  ,  0.0423051 , -0.02483431, -0.00097876,
         -0.04993521,  0.02311223],
        [ 0.00316459,  0.03200897, -0.02498647,  0.04236316,
         -0.018163  ,  0.0423051 , -0.02483431, -0.00097876,
         -0.04993521,  0.02311223],
        [-0.01676697, -0.03454573,  0.0198954 ,  0.02936431,
          0.01123331,  0.04145045,  0.04648289,  0.03914342,
         -0.04968213,  0.04895056],
        [ 0.01721871,  0.00998025, -0.00494791,  0.03398434,
         -0.02912877, -0.01955065, -0.04308022,  0.04685971,
          0.03651178, -0.01404995],
        [ 0.02079454,  0.00735513,  0.00693585, -0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0,  892, 2802, 6729, 4444])

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 61ms/step


array([[ 0.00316459,  0.03200897, -0.02498647,  0.04236316, -0.018163  ,
         0.0423051 , -0.02483431, -0.00097876, -0.04993521,  0.02311223],
       [ 0.00316459,  0.03200897, -0.02498647,  0.04236316, -0.018163  ,
         0.0423051 , -0.02483431, -0.00097876, -0.04993521,  0.02311223],
       [ 0.00316459,  0.03200897, -0.02498647,  0.04236316, -0.018163  ,
         0.0423051 , -0.02483431, -0.00097876, -0.04993521,  0.02311223],
       [ 0.00316459,  0.03200897, -0.02498647,  0.04236316, -0.018163  ,
         0.0423051 , -0.02483431, -0.00097876, -0.04993521,  0.02311223],
       [-0.01676697, -0.03454573,  0.0198954 ,  0.02936431,  0.01123331,
         0.04145045,  0.04648289,  0.03914342, -0.04968213,  0.04895056],
       [ 0.01721871,  0.00998025, -0.00494791,  0.03398434, -0.02912877,
        -0.01955065, -0.04308022,  0.04685971,  0.03651178, -0.01404995],
       [ 0.02079454,  0.00735513,  0.00693585, -0.00931556,  0.00447096,
         0.01771133, -0.03321551, -0.01299604